# See https://cloud.google.com/appengine/docs/standard/php/config/appref for a
# complete list of `app.yaml` directives.

runtime: php81

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  # Enables the load of the react app modules, including the icon svg
  - url: /(.*\.(svg|js|css))$
    static_files: react/\1
    upload: react/(.*\.(svg|js|css))$

  # Enables load of react app via index.html on /start
  # and the browser refresh button to work on /admin etc.
  # Have to ensure that /api/* is not matched here (e.g. /api/userlist/...)
  - url: /start/[0-9a-fA-F]{32}|/admin.*|/owner/.*|^/user/.*|^/userlist/.*
    static_files: react/index.html
    upload: react/index.html

  # All URLs ending in .gif .png or .jpg are treated as paths to
  # static files in the static/ directory. The URL pattern is a
  # regular expression, with a grouping that is inserted into the
  # path to the file.
  # If these requests are not handled here, the PHP application will handle them and fail
  # causing a loss of session data
  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  # Every other request is handled by the PHP application
  - url: /.*
    script: auto
