# See https://cloud.google.com/appengine/docs/standard/php/config/appref for a
# complete list of `app.yaml` directives.

runtime: php81

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /(.*\.(svg|js|css))$
    static_files: react/\1
    upload: react/(.*\.(svg|js|css))$

  # Enables load of react app on /start and the refresh button to work on /admin etc.
  - url: /start/[0-9a-fA-F]{32}|/admin.*|/owner/.*|/user/.*$
    static_files: react/index.html
    upload: react/index.html

  - url: /.*
    script: auto
